---
AllCops:
  Include:
  - "**/*.gemspec"
  - "**/Rakefile"
  - "**/Gemfile"
  - "**/Vagrantfile"
  - "**/config.ru"
  Exclude:
  - vendor/**/*
  - db/schema.rb
  DisabledByDefault: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/BlockAlignment:
  Enabled: true
Lint/CircularArgumentReference:
  Enabled: true
Lint/ConditionPosition:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/DefEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: false
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/EachWithObjectArgument:
  Enabled: true
Lint/ElseLayout:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: keyword
  AutoCorrect: false
Lint/EndInMethod:
  Enabled: true
Lint/EnsureReturn:
  Enabled: true
Security/Eval:
  Enabled: true
Lint/FormatParameterMismatch:
  Enabled: true
Lint/HandleExceptions:
  Enabled: true
Lint/InvalidCharacterLiteral:
  Enabled: true
Lint/LiteralInCondition:
  Enabled: true
Lint/LiteralInInterpolation:
  Enabled: true
  AutoCorrect: false
Lint/NestedMethodDefinition:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Lint/RequireParentheses:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Lint/StringConversionInInterpolation:
  Enabled: true
Lint/UnneededDisable:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/UselessComparison:
  Enabled: true
Lint/UselessElseWithoutRescue:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true
Lint/Void:
  Enabled: true
Metrics/AbcSize:
  Reference: http://c2.com/cgi/wiki?AbcMetric
  Enabled: true
  Max: 20
Metrics/BlockNesting:
  Enabled: true
  Max: 6
Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 500
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10
Metrics/LineLength:
  Enabled: true
  Max: 120
  AllowURI: true
  URISchemes:
  - http
  - https
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20
Metrics/ModuleLength:
  Enabled: true
  CountComments: false
  Max: 500
Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10
Performance/Count:
  Enabled: true
Performance/Detect:
  Reference: https://github.com/JuanitoFatas/fast-ruby#enumerabledetect-vs-enumerableselectfirst-code
  Enabled: true
Performance/FlatMap:
  Reference: https://github.com/JuanitoFatas/fast-ruby#enumerablemaparrayflatten-vs-enumerableflat_map-code
  Enabled: true
  EnabledForFlattenWithoutParams: false
Performance/Sample:
  Reference: https://github.com/JuanitoFatas/fast-ruby#arrayshufflefirst-vs-arraysample-code
  Enabled: true
Rails/ActionFilter:
  Enabled: true
  EnforcedStyle: action
  Include:
  - app/controllers/**/*.rb
Rails/Date:
  Enabled: true
  EnforcedStyle: flexible
Rails/Delegate:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/Output:
  Enabled: true
  Include:
  - app/**/*.rb
  - config/**/*.rb
  - db/**/*.rb
  - lib/**/*.rb
Rails/ReadWriteAttribute:
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/ScopeArgs:
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/TimeZone:
  Reference: http://danilenko.org/2012/7/6/rails_timezones
  Enabled: true
  EnforcedStyle: flexible
Rails/Validation:
  Enabled: true
  Include:
  - app/models/**/*.rb
Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
Naming/AccessorMethodName:
  Enabled: true
Style/Alias:
  Enabled: true
Layout/AlignArray:
  Enabled: true
Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_first_parameter
Style/AndOr:
  Enabled: true
  EnforcedStyle: always
Style/ArrayJoin:
  Enabled: true
Naming/AsciiIdentifiers:
  Enabled: true
Style/Attr:
  Enabled: true
Style/BeginBlock:
  Enabled: true
Style/BlockComments:
  Enabled: true
Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based
  ProceduralMethods:
  - benchmark
  - bm
  - bmbm
  - create
  - each_with_object
  - measure
  - new
  - realtime
  - tap
  - with_object
  FunctionalMethods:
  - let
  - let!
  - subject
  - watch
  IgnoredMethods:
  - lambda
  - proc
  - it
Layout/BlockEndNewline:
  Enabled: true
Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: no_braces
Style/CaseEquality:
  Enabled: true
Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: case
  IndentOneStep: false
Style/CharacterLiteral:
  Enabled: true
Naming/ClassAndModuleCamelCase:
  Enabled: true
Style/ClassMethods:
  Enabled: true
Style/ClassVars:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Style/ColonMethodCall:
  Enabled: true
Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: backticks
  AllowInnerBackticks: false
Style/CommentAnnotation:
  Enabled: true
  Keywords:
  - TODO
  - FIXME
  - OPTIMIZE
  - HACK
  - REVIEW
Layout/CommentIndentation:
  Enabled: true
Naming/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing
Style/DoubleNegation:
  Enabled: true
Layout/ElseAlignment:
  Enabled: true
Style/EmptyElse:
  Enabled: true
  EnforcedStyle: both
Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
Style/EmptyLiteral:
  Enabled: true
Style/Encoding:
  Enabled: true
  EnforcedStyle: when_needed
  AutoCorrectEncodingComment: "# encoding: utf-8"
Style/EndBlock:
  Enabled: true
Layout/EndOfLine:
  Enabled: true
Style/EvenOdd:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
Naming:
  Enabled: true
  Exclude: []
Layout:
  Enabled: true
  EnforcedStyle: special_for_inner_method_call_in_parentheses
Style/FlipFlop:
  Enabled: true
Style/For:
  Enabled: true
  EnforcedStyle: each
Style/GlobalVars:
  Reference: http://www.zenspider.com/Languages/Ruby/QuickRef.html
  Enabled: true
  AllowedVariables: []
Style/IfWithSemicolon:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
Layout:
  Enabled: true
  EnforcedStyle: normal
Layout:
  Enabled: true
  Width: 2
Style/InfiniteLoop:
  Enabled: true
Style/Lambda:
  Enabled: true
Style/LambdaCall:
  Enabled: true
  EnforcedStyle: call
Layout:
  Enabled: true
Style/LineEndConcatenation:
  Enabled: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
Naming:
  Enabled: true
  EnforcedStyle: snake_case
Style/ModuleFunction:
  Enabled: true
Layout:
  Enabled: true
Style/MultilineIfThen:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: aligned
Style/MultilineTernaryOperator:
  Enabled: true
Style/NestedTernaryOperator:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/Not:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
  MinDigits: 5
Style/OneLineConditional:
  Enabled: true
Style/OptionalArguments:
  Enabled: true
Style/ParenthesesAroundCondition:
  Enabled: true
  AllowSafeAssignment: true
Naming:
  Enabled: true
  NamePrefix:
  - is_
  - has_
  - have_
  NamePrefixBlacklist:
  - is_
  - has_
  - have_
Style/Proc:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
Style/RedundantBegin:
  Enabled: true
Style/RedundantException:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: slashes
  AllowInnerSlashes: false
Layout:
  Enabled: true
Style/RescueModifier:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: false
Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise
Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyleInsidePipes: no_space
Layout:
  Enabled: true
  EnforcedStyle: space
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: space
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout:
  Enabled: true
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: no_space
Style/StructInheritance:
  Enabled: true
Style/SymbolLiteral:
  Enabled: true
Style/SymbolProc:
  Enabled: true
  IgnoredMethods:
  - respond_to
Layout:
  Enabled: true
Layout:
  Enabled: true
  EnforcedStyle: final_newline
Style/TrailingCommaInLiteral:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Style/TrailingUnderscoreVariable:
  Enabled: true
Layout:
  Enabled: true
Style/UnlessElse:
  Enabled: true
Style/UnneededPercentQ:
  Enabled: true
Style/VariableInterpolation:
  Enabled: true
Naming:
  Enabled: true
  EnforcedStyle: snake_case
Style/WhenThen:
  Enabled: true
Style/WhileUntilDo:
  Enabled: true
Layout/IndentHeredoc:
  Enabled: false
Naming/PredicateName:
  Enabled: false
