source 'https://rubygems.org'

gem 'git'
gem 'rake'
gem 'sinatra'

gem 'minitest'
gem 'minitest-reporters'

gem 'rack-test'
gem 'rubocop', '0.50.0'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'awesome_print'
end
