source 'https://rubygems.org'

gem 'sinatra'
gem 'minitest'
gem 'rake'

gem 'rack-test'
gem 'rubocop', '0.50.0'

gem 'git'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'awesome_print'
end
