# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.5.1"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - ruby -v                                   # Print out ruby version for debugging
  - git config --global user.email "testuser@example.com"
  - git config --global user.name "Test User"
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - cd cli
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - cd ..
  - cd sinatra
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - cd ..

cli_rubocop:
  script:
    - cd cli
    - bundle exec rake rubocop

cli_tests:
  script:
    - cd cli
    - bundle exec rake test

sinatra_rubocop:
  script:
    - cd sinatra
    - bundle exec rake rubocop

sinatra_tests:
  script:
    - cd sinatra
    - bundle exec rake test
